const missions=[
{title:"성문의 암호",location:"공북문",story:"첫 번째 단서는 진주성의 문에서 시작된다.",photo:"공북문이 보이도록 현장 사진을 촬영하세요.",question:"[임시 문제] 이 장소의 이름을 입력하세요.",answers:["공북문"]},
{title:"장군의 이름",location:"김시민 장군 관련 장소",story:"성을 지킨 장군의 기록을 찾아라.",photo:"김시민 장군과 관련된 장소 또는 안내물이 나오도록 촬영하세요.",question:"[임시 문제] 진주대첩을 이끈 장군의 이름은?",answers:["김시민","김시민장군"]},
{title:"관문의 기록",location:"영남포정사",story:"오래된 건물에서 세 번째 단서를 찾아라.",photo:"영남포정사가 보이도록 촬영하세요.",question:"[임시 문제] 현재 장소의 이름은?",answers:["영남포정사"]},
{title:"누각의 단서",location:"촉석루",story:"남강을 내려다보는 누각에 기록이 남아 있다.",photo:"촉석루가 확인되도록 촬영하세요.",question:"[임시 문제] 진주성의 대표적인 누각 이름은?",answers:["촉석루"]},
{title:"바위에 남은 기억",location:"의암",story:"강가에 남겨진 이야기가 다섯 번째 단서다.",photo:"의암 또는 안내가 확인되도록 촬영하세요.",question:"[임시 문제] 이 바위의 이름은?",answers:["의암"]},
{title:"최종 암호",location:"최종 집결지",story:"마지막 현장 기록을 남기고 비밀문서를 완성하라.",photo:"진주성 현장 인증사진을 촬영하세요.",question:"[임시 문제] 오늘 탐험한 성의 이름은?",answers:["진주성"]}
];
const $=id=>document.getElementById(id);
const cfg=window.APP_CONFIG||{};
const configured=cfg.SUPABASE_PUBLISHABLE_KEY && !cfg.SUPABASE_PUBLISHABLE_KEY.includes("여기에_");
const sb=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY):null;
let state=JSON.parse(localStorage.getItem("jinjuSecretStateV3")||"null")||{started:false,grade:"2",classNo:"",team:"",teamId:null,completed:[]};
let current=0,file=null,photoURL=null;
const save=()=>localStorage.setItem("jinjuSecretStateV3",JSON.stringify(state));
const norm=s=>s.trim().replace(/\s/g,"").toLowerCase();
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");scrollTo(0,0)}
function render(){ $("teamLabel").textContent=`${state.grade}학년 ${state.classNo}반 · ${state.team}`;$("progressText").textContent=`${state.completed.length} / 6`;$("progressBar").style.width=`${state.completed.length/6*100}%`;$("missionList").innerHTML="";
missions.forEach((m,i)=>{let done=state.completed.includes(i),unlock=i===0||state.completed.includes(i-1),d=document.createElement("div");d.className=`mission-card ${done?"done":""} ${!unlock?"locked":""}`;d.innerHTML=`<button ${unlock?"":"disabled"}><span class="num">${String(i+1).padStart(2,"0")}</span><span><h3>${m.title}</h3><p>${unlock?m.location:"이전 임무를 완료하세요"}</p></span><span class="state">${done?"✓":unlock?"→":"🔒"}</span></button>`;if(unlock)d.querySelector("button").onclick=()=>openMission(i);$("missionList").appendChild(d)})}
function photoReady(ok){$("questionBox").classList.toggle("disabled",!ok);$("answerInput").disabled=!ok;$("answerBtn").disabled=!ok;$("photoStatus").textContent=ok?"✓ 사진 준비 완료. 답안을 입력하세요.":"사진을 촬영해야 문제를 풀 수 있습니다.";$("photoStatus").classList.toggle("ok",ok)}
function openMission(i){current=i;file=null;if(photoURL){URL.revokeObjectURL(photoURL);photoURL=null}let m=missions[i];$("missionNumber").textContent=`MISSION ${String(i+1).padStart(2,"0")}`;$("missionTitle").textContent=m.title;$("missionStory").textContent=m.story;$("missionLocation").textContent=m.location;$("photoInstruction").textContent=m.photo;$("missionQuestion").textContent=m.question;$("answerInput").value="";$("feedback").textContent="";$("photoInput").value="";$("previewWrap").classList.remove("show");$("missionStamp").classList.toggle("show",state.completed.includes(i));photoReady(state.completed.includes(i));show("detailScreen")}
$("cameraBtn").onclick=()=>$("photoInput").click();$("retakeBtn").onclick=()=>$("photoInput").click();
$("photoInput").onchange=e=>{file=e.target.files?.[0]||null;if(!file)return;if(file.size>5*1024*1024){alert("사진은 5MB 이하로 촬영/선택해주세요.");file=null;return}if(photoURL)URL.revokeObjectURL(photoURL);photoURL=URL.createObjectURL(file);$("photoPreview").src=photoURL;$("previewWrap").classList.add("show");photoReady(true)};
$("startBtn").onclick=async()=>{let team=$("teamName").value.trim(),cl=$("classNo").value.trim();if(!team||!cl){$("startStatus").textContent="반과 팀명을 입력해주세요.";return}if(!configured){$("startStatus").textContent="config.js에 Publishable key를 먼저 입력해주세요.";return}$("startBtn").disabled=true;$("startStatus").textContent="팀을 등록하는 중...";
try{const {data,error}=await sb.from("teams").insert({grade:$("grade").value,class_no:cl,team_name:team}).select("id").single();if(error)throw error;state={started:true,grade:$("grade").value,classNo:cl,team,teamId:data.id,completed:[]};save();render();show("missionScreen")}catch(e){$("startStatus").textContent="연결 오류: "+e.message}finally{$("startBtn").disabled=false}};
$("answerBtn").onclick=async()=>{if(!file && !state.completed.includes(current))return;let ans=$("answerInput").value.trim(),m=missions[current];if(!ans){$("feedback").textContent="답안을 입력해주세요.";return}let correct=m.answers.some(x=>norm(x)===norm(ans));if(!correct){$("feedback").textContent="암호가 맞지 않습니다. 현장을 다시 관찰해보세요.";return}$("answerBtn").disabled=true;$("feedback").textContent="사진과 답안을 제출하는 중...";
try{let photoPath=null;if(file){let ext=(file.name.split(".").pop()||"jpg").toLowerCase();let safeExt=["jpg","jpeg","png","webp"].includes(ext)?ext:"jpg";photoPath=`grade${state.grade}-class${state.classNo}-team${state.teamId}/mission-${current+1}-${Date.now()}.${safeExt}`;let {error:upErr}=await sb.storage.from("mission-photos").upload(photoPath,file,{upsert:false,contentType:file.type});if(upErr)throw upErr}
let {error:dbErr}=await sb.from("mission_submissions").insert({team_id:state.teamId,mission_no:current+1,answer:ans,is_correct:true,photo_path:photoPath});if(dbErr)throw dbErr;
if(!state.completed.includes(current))state.completed.push(current);state.completed.sort((a,b)=>a-b);save();$("missionStamp").classList.add("show");$("feedback").textContent="✓ 제출 완료! Supabase에 기록되었습니다.";setTimeout(()=>{if(state.completed.length===6){$("completeTeam").textContent=`${state.team}, 모든 임무를 완료했습니다.`;show("completeScreen")}else{render();show("missionScreen")}},900)
}catch(e){$("feedback").textContent="제출 오류: "+e.message;$("answerBtn").disabled=false}};
$("backBtn").onclick=()=>{render();show("missionScreen")};$("homeBtn").onclick=()=>{render();show("missionScreen")};$("resetBtn").onclick=()=>{if(confirm("이 기기의 진행 기록을 초기화할까요? (서버 제출 기록은 삭제되지 않습니다.)")){localStorage.removeItem("jinjuSecretStateV3");location.reload()}};
if(state.started){render();show(state.completed.length===6?"completeScreen":"missionScreen");if(state.completed.length===6)$("completeTeam").textContent=`${state.team}, 모든 임무를 완료했습니다.`}
